# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20170304_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='name',
        ),
        migrations.AddField(
            model_name='equipment',
            name='label',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
